spring:
  security:
    oauth2:
      client:
        registration:
          ddd:
            client-id: ddd
            client-secret: ddd
            # isValidRedirectUri
            redirect-uri: 'http://mac.dou.com:8080/authorize/client'
            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_post
            client-authentication-method: client_secret_basic
            scope: msg.read,msg.write
        provider:
          ddd:
            # provider 尽量用域名,不要用localhost或者IP,而且要和well-known接口中保持一致
            issuer-uri: http://auth-server.com:9000
#            authorization-uri: http://localhost:9000/oauth2/authorize
#            token-uri: http://localhost:9000/oauth2/token
#            user-info-uri: http://your-userinfo-endpoiont
#            user-name-attribute: username
#            user-info-authentication-method: GET

# 方便调试
logging:
  level:
#    org.springframework.web: trace
    org.springframework.security: debug
    org.springframework.security.oauth2: debug